export enum FILTER {
  ALL = 'ALL',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED'
}

export enum ADD_TASK {
  REQUEST = 'ADD_TASK',
  SUCCESS = 'ADD_SUCCESS',
  FAILED = 'ADD_FAILED'
}

export enum DELETE_TASK {
  REQUEST = 'DELETE_TASK',
  SUCCESS = 'DELETE_SUCCESS',
  FAILED = 'DELETE_FAILED'
}

export enum CHECK_TASK {
  REQUEST = 'CHECK_TASK',
  SUCCESS = 'CHECK_SUCCESS',
  FAILED = 'CHECK_FAILED'
}

export enum EDIT_TASK {
  REQUEST = 'EDIT_TASK',
  SUCCESS = 'EDIT_SUCCESS',
  FAILED = 'EDIT_FAILED'
}

export enum CHANGE_VALUE_TASK {
  REQUEST = 'CHANGE_VALUE_TASK',
  SUCCESS = 'CHANGE_VALUE_TASK_SUCCESS',
  FAILED = 'CHANGE_VALUE_FAILED'
}

export enum ON_BLUR_TASK {
  REQUEST = 'ON_BLUR_TASK',
  SUCCESS = 'ON_BLUR_SUCCESS',
  FAILED = 'ON_BLUR_FAILED'
}

export enum CHECK_ALL_TASKS {
  REQUEST = 'CHECK_ALL_TASKS',
  SUCCESS = 'CHECK_ALL_SUCCESS',
  FAILED = 'CHECK_ALL_FAILED'
}

export enum CLEAR_COMPLETED_TASKS {
  REQUEST = 'CLEAR_COMPLETED_TASKS',
  SUCCESS = 'CLEAR_COMPLETED_SUCCESS',
  FAILED = 'CLEAR_COMPLETED_FAILED'
}

export enum GET_TASKS {
  REQUEST = 'GET_TASKS',
  SUCCESS = 'GET_TASKS_SUCCESS',
  FAILED = 'GET_TASKS_FAILED'
}
