export enum REGISTR_USER {
    REQUEST = 'REGISTR_USER',
    SUCCESS = 'REGISTR_USER_SUCCESS',
    FAILED = 'REGISTR_USER_FAILED'
  }
  
  export enum LOGIN_USER {
    REQUEST = 'LOGIN_USER',
    SUCCESS = 'LOGIN_USER_SUCCESS',
    FAILED = 'LOGIN_USER_FAILED'
  }
  
  export enum LOGOUT_USER {
    REQUEST = 'LOGOUT_USER',
    SUCCESS = 'LOGOUT_USER_SUCCESS',
    FAILED = 'LOGOUT_USER_FAILED'
  }
  
  export enum START_APP {
    SUCCESS = 'START_APP_SUCCESS',
  }